function lazyLoadBg(t,e){$("<img/>").attr("src",e).on({load:function(){$(this).remove(),$(t).css("backgroundImage","url("+e+")"),$(t).css("opacity","1")},error:function(){$(this).remove()}})}$(document).on("scroll",function(){$(document).scrollTop()>5?$(".main-nav").addClass("shrink"):$(".main-nav").removeClass("shrink")}),$("h1,h2,h3,h4,h5,h6,p,a").each(function(){$(this).html($(this).html().replace(/\s([^\s<]+)\s*$/,"&nbsp;$1"))}),function(){var t=$(".fader figure"),e=t.length,i=0
setInterval(function(){$(t[i]).removeClass("show"),++i,i>=e&&(i=0),$(t[i]).addClass("show")},3e3)}(),$(window).scroll(function(){var t=$(window),e=$("main"),i=$(".panel"),o=t.scrollTop()+t.height()/3
i.each(function(){var t=$(this)
t.position().top<=o&&t.position().top+t.height()>o&&(e.removeClass(function(t,e){return(e.match(/(^|\s)color-\S+/g)||[]).join(" ")}),e.addClass("color-"+$(this).data("color")))})}).scroll(),$('a[href^="#"]').on("click",function(t){t.preventDefault()
var e=this.hash,i=$(e)
$("html, body").stop().animate({scrollTop:i.offset().top},500,"swing",function(){window.location.hash=e})}),$(function(t){"use strict"
t.fn.darthFader=function(e){function i(){l=l>=s.length-1?0:l+1,o()}function o(){d&&clearTimeout(d),r.dots&&(c.removeClass(r.activeClass),c.eq(l).addClass(r.activeClass)),s.removeClass(r.activeClass),s.eq(l).addClass(r.activeClass),r.waitTime&&(d=setTimeout(function(){i()},r.waitTime+r.speed))}var n={waitTime:!1,dots:!0,items:".item",activeClass:"active",speed:200},r=t.extend(n,e),a=this,s=a.find(r.items),l=0,d=!1
if(r.dots){var c=t(Array(s.length+1).join("<li></li>")).on("click",function(){l=t(this).index(),o()})
c.first().addClass(r.activeClass),t("<ul></ul>").addClass("fader-dots").append(c).appendTo(a)}r.waitTime&&(d=setTimeout(function(){i()},r.waitTime))}}(jQuery)),$(".fader").darthFader({speed:1,waitTime:2e3})
var Glitch=function(){function t(){this._text=document.querySelector(".heading"),this._filter=document.querySelector(".svg-filters"),this._turb=this._filter.querySelector("#filter feTurbulence"),this._turbVal={val:1e-6},this._turbValX={val:1e-6},this.createTimeline()}return t.prototype.createTimeline=function(){var t=this
this.timeline=new TimelineMax({repeat:9999,onUpdate:function(){t._turb.setAttribute("baseFrequency",t._turbVal.val+" "+t._turbValX.val)}}),this.timeline.to(this._turbValX,.1,{val:.3,ease:Power0.easeNone},1),this.timeline.set(this._turbValX,{val:0,ease:Power0.easeNone},2)},t}()
new Glitch,$(".modal-btn").click(function(t){$(".modal").addClass("active"),t.preventDefault()}),$(".close-btn").click(function(t){$(".modal").removeClass("active"),t.preventDefault()}),$(".lazy").each(function(t,e){lazyLoadBg(e,$(e).data("src"))}),function(t,e){function i(){C=B=k=x=R=W=N}function o(t,e){for(var i in e)e.hasOwnProperty(i)&&(t[i]=e[i])}function n(t){return parseFloat(t)||0}function r(){S={top:e.pageYOffset,left:e.pageXOffset}}function a(){return e.pageXOffset!=S.left?(r(),void k()):void(e.pageYOffset!=S.top&&(r(),l()))}function s(t){setTimeout(function(){e.pageYOffset!=S.top&&(S.top=e.pageYOffset,l())},0)}function l(){for(var t=_.length-1;t>=0;t--)d(_[t])}function d(t){if(t.inited){var e=S.top<=t.limit.start?0:S.top>=t.limit.end?2:1
t.mode!=e&&m(t,e)}}function c(){for(var t=_.length-1;t>=0;t--)if(_[t].inited){var e=Math.abs(w(_[t].clone)-_[t].docOffsetTop),i=Math.abs(_[t].parent.node.offsetHeight-_[t].parent.height)
if(e>=2||i>=2)return!1}return!0}function f(t){isNaN(parseFloat(t.computed.top))||t.isCell||"none"==t.computed.display||(t.inited=!0,t.clone||g(t),"absolute"!=t.parent.computed.position&&"relative"!=t.parent.computed.position&&(t.parent.node.style.position="relative"),d(t),t.parent.height=t.parent.node.offsetHeight,t.docOffsetTop=w(t.clone))}function p(t){var e=!0
t.clone&&v(t),o(t.node.style,t.css)
for(var i=_.length-1;i>=0;i--)if(_[i].node!==t.node&&_[i].parent.node===t.parent.node){e=!1
break}e&&(t.parent.node.style.position=t.parent.css.position),t.mode=-1}function h(){for(var t=_.length-1;t>=0;t--)f(_[t])}function u(){for(var t=_.length-1;t>=0;t--)p(_[t])}function m(t,e){var i=t.node.style
switch(e){case 0:i.position="absolute",i.left=t.offset.left+"px",i.right=t.offset.right+"px",i.top=t.offset.top+"px",i.bottom="auto",i.width="auto",i.marginLeft=0,i.marginRight=0,i.marginTop=0
break
case 1:i.position="fixed",i.left=t.box.left+"px",i.right=t.box.right+"px",i.top=t.css.top,i.bottom="auto",i.width="auto",i.marginLeft=0,i.marginRight=0,i.marginTop=0
break
case 2:i.position="absolute",i.left=t.offset.left+"px",i.right=t.offset.right+"px",i.top="auto",i.bottom=0,i.width="auto",i.marginLeft=0,i.marginRight=0}t.mode=e}function g(t){t.clone=document.createElement("div")
var e=t.node.nextSibling||t.node,i=t.clone.style
i.height=t.height+"px",i.width=t.width+"px",i.marginTop=t.computed.marginTop,i.marginBottom=t.computed.marginBottom,i.marginLeft=t.computed.marginLeft,i.marginRight=t.computed.marginRight,i.padding=i.border=i.borderSpacing=0,i.fontSize="1em",i.position="static",i.cssFloat=t.computed.cssFloat,t.node.parentNode.insertBefore(t.clone,e)}function v(t){t.clone.parentNode.removeChild(t.clone),t.clone=void 0}function b(t){var e=getComputedStyle(t),i=t.parentNode,o=getComputedStyle(i),r=t.style.position
t.style.position="relative"
var a={top:e.top,marginTop:e.marginTop,marginBottom:e.marginBottom,marginLeft:e.marginLeft,marginRight:e.marginRight,cssFloat:e.cssFloat,display:e.display},s={top:n(e.top),marginBottom:n(e.marginBottom),paddingLeft:n(e.paddingLeft),paddingRight:n(e.paddingRight),borderLeftWidth:n(e.borderLeftWidth),borderRightWidth:n(e.borderRightWidth)}
t.style.position=r
var l={position:t.style.position,top:t.style.top,bottom:t.style.bottom,left:t.style.left,right:t.style.right,width:t.style.width,marginTop:t.style.marginTop,marginLeft:t.style.marginLeft,marginRight:t.style.marginRight},d=y(t),c=y(i),f={node:i,css:{position:i.style.position},computed:{position:o.position},numeric:{borderLeftWidth:n(o.borderLeftWidth),borderRightWidth:n(o.borderRightWidth),borderTopWidth:n(o.borderTopWidth),borderBottomWidth:n(o.borderBottomWidth)}},p={node:t,box:{left:d.win.left,right:z.clientWidth-d.win.right},offset:{top:d.win.top-c.win.top-f.numeric.borderTopWidth,left:d.win.left-c.win.left-f.numeric.borderLeftWidth,right:-d.win.right+c.win.right-f.numeric.borderRightWidth},css:l,isCell:"table-cell"==e.display,computed:a,numeric:s,width:d.win.right-d.win.left,height:d.win.bottom-d.win.top,mode:-1,inited:!1,parent:f,limit:{start:d.doc.top-s.top,end:c.doc.top+i.offsetHeight-f.numeric.borderBottomWidth-t.offsetHeight-s.top-s.marginBottom}}
return p}function w(t){for(var e=0;t;)e+=t.offsetTop,t=t.offsetParent
return e}function y(t){var i=t.getBoundingClientRect()
return{doc:{top:i.top+e.pageYOffset,left:i.left+e.pageXOffset},win:i}}function $(){O=setInterval(function(){!c()&&k()},500)}function T(){clearInterval(O)}function L(){F&&(document[X]?T():$())}function C(){F||(r(),h(),e.addEventListener("scroll",a),e.addEventListener("wheel",s),e.addEventListener("resize",k),e.addEventListener("orientationchange",k),t.addEventListener(q,L),$(),F=!0)}function k(){if(F){u()
for(var t=_.length-1;t>=0;t--)_[t]=b(_[t].node)
h()}}function x(){e.removeEventListener("scroll",a),e.removeEventListener("wheel",s),e.removeEventListener("resize",k),e.removeEventListener("orientationchange",k),t.removeEventListener(q,L),T(),F=!1}function R(){x(),u()}function W(){for(R();_.length;)_.pop()}function B(t){for(var e=_.length-1;e>=0;e--)if(_[e].node===t)return
var i=b(t)
_.push(i),F?f(i):C()}function E(t){for(var e=_.length-1;e>=0;e--)_[e].node===t&&(p(_[e]),_.splice(e,1))}var S,O,_=[],F=!1,z=t.documentElement,N=function(){},X="hidden",q="visibilitychange"
void 0!==t.webkitHidden&&(X="webkitHidden",q="webkitvisibilitychange"),e.getComputedStyle||i()
for(var H=["","-webkit-","-moz-","-ms-"],V=document.createElement("div"),j=H.length-1;j>=0;j--){try{V.style.position=H[j]+"sticky"}catch(Y){}""!=V.style.position&&i()}r(),e.Stickyfill={stickies:_,add:B,remove:E,init:C,rebuild:k,pause:x,stop:R,kill:W}}(document,window),window.jQuery&&!function(t){t.fn.Stickyfill=function(t){return this.each(function(){Stickyfill.add(this)}),this}}(window.jQuery)
